Implement Copy email List Section
HackBeanpot/internal-tools pull request #133
Opened 2023-06-30 22:42 UTC by kzeng24

Fixes #132 

In this new section, a user will be able to select a cabin from a dropdown and hit the copy button icon to copy a string of emails associated with that cabin!

 Implement the design [here](https://www.figma.com/file/Ur8DMCmxLx7WMKqHoEChR3/Cabin-Sorting?type=design&node-id=102-632&mode=design&t=wWOnY8zbz8f2g9Ue-0) using mui components entirely (dropdown title should be "Cabin")
 For functionality, use dummy data to copy to the user's clipboard
 Once copied, the copy icon button should turn into the check mark icon (non-clickable)
 Once copied, a Snackbar should appear in the top right stating "Copied to Clipboard"
 Check icon should be green
 If the user goes to select another cabin, the check mark icon should turn back into the copy icon button

2023-07-03 04:48 UTC, zhangcry requested changes
Great work!!! One thing I was wondering about was the use of React.Fragment. To be clear, I didn't know anything about it before doing this review. I saw on some resources that you could use <> ... </> instead. Is there a reason you chose to write out the name rather than using the shorthand?

2023-07-03 19:33 UTC, mike10911 requested changes
This is soo good guys!!! A few changes below:
- Update the mui select component to have a label + helper text (https://codesandbox.io/s/24jqtk?file=/demo.tsx)
- "Cabin" should not be a option when selecting, rather it should be the label/helper text
- For the copy/check icons use mui icons and remove react icons as a dependency
- I am not realizing that putting the snackbar in the top right covers the signout button. Let move it to the bottom left

2023-07-03 19:33 UTC, mike10911 commented on ui/components/templateDropdown/cabinDropdown.tsx
> +              navigator.clipboard.writeText(selectedItem)
We'd like to return the string of emails associated with this cabin, not the cabin name. Find a way to pass these down!

2023-07-03 19:33 UTC, mike10911 commented on ui/components/templateDropdown/cabinDropdown.tsx
> +  // if true, the checkmark will appear
remove these comments

2023-07-03 19:33 UTC, mike10911 commented on ui/components/templateDropdown/cabinDropdown.tsx
> +  const [selectedItem, setSelectedItem] = React.useState('')
Let's call this selectedCabin to be more precise

2023-07-03 19:33 UTC, mike10911 commented on ui/components/snackBar/topRightSnackBar.tsx
> +import * as React from 'react'
Let's abstract this component to be any position snack bar, receiving message, and position props.

2023-07-03 19:37 UTC, mike10911 requested changes
Also plz create a proper PR comment detailing changes, you should NEVER just copy-paste the issue details. As it is a frontend ticket, be sure to include screenshots/video

2023-07-05 03:49 UTC, mike10911 approved these changes
OMG, GREAT JOB WITH ALL THE CHANGES!!! Approving with a couple small changes.

2023-07-05 03:49 UTC, mike10911 commented on ui/components/templateDropdown/selectedCabin.tsx
> +            message={'Copied to Clipboard'}
this should just be a string

2023-07-05 03:49 UTC, mike10911 commented on ui/components/templateDropdown/selectedCabin.tsx
> +                cabinValues[selectedItem].toString()
remove toString

2023-07-06 17:03 UTC, zhangcry approved these changes
great work!!!

2023-07-07 21:35 UTC, mike10911 requested changes
Sorry, I missed something! The copy icon should only appear when the user selects a cabin, to ensure we don't copy down undefined.

2023-07-08 19:00 UTC, mike10911 requested changes
When you addressed merge conflicts, the link to the cabin page was removed!

2023-07-11 04:05 UTC, mike10911 approved these changes
LGTM!!!!

2023-07-11 14:03 UTC, merged