[Feature] Add Link From Cabin Sorting Page to Internal Tools Dashboard
HackBeanpot/internal-tools pull request #136
Opened 2023-07-07 19:17 UTC by kzeng24

Fixes #95 
Follows design [here](https://www.figma.com/file/Ur8DMCmxLx7WMKqHoEChR3/Cabin-Sorting?type=design&node-id=0-1&mode=design&t=tq0d0CMpLKcIyGMD-0)
- Created green arrow button that leads user back to internal tools dashboard
- Green arrow will turn dark blue on hover
- Appears on signature maker page, email sender page and cabin sorting page 

![Screen Shot 2023-07-07 at 3 15 06 PM](https://github.com/HackBeanpot/internal-tools/assets/52469441/0016e395-dcad-4334-8c0a-860d01e5b304)
![Screen Shot 2023-07-07 at 3 15 48 PM](https://github.com/HackBeanpot/internal-tools/assets/52469441/5ff1aa2f-952e-42f9-a1ab-f7cf089f96e7)
![Screen Shot 2023-07-07 at 3 16 06 PM](https://github.com/HackBeanpot/internal-tools/assets/52469441/2da40652-6b2c-4399-b286-b4d2056e3292)

On hover:
![Screen Shot 2023-07-07 at 3 15 23 PM](https://github.com/HackBeanpot/internal-tools/assets/52469441/0ee01f24-2026-4d47-8465-adffe53edc6d)

2023-07-07 19:33 UTC, Mandy-cyber approved these changes
LGTM! 🔥 🔥

2023-07-08 20:12 UTC, mike10911 requested changes
Such a slay! Comments below:

2023-07-08 20:12 UTC, mike10911 commented on ui/pages/cabinSorting.tsx
> +    color: isHover ? 'darkblue' : 'green'
Let's give this some transition to make the color changes a bit smoother!

2023-07-08 20:12 UTC, mike10911 commented on ui/pages/cabinSorting.tsx
> +          </Link>
Since we are using this component multiple times, let's abstract this into its own component!

2023-07-08 20:12 UTC, mike10911 commented on ui/pages/cabinSorting.tsx
> +    color: isHover ? 'darkblue' : 'green'
Can we use the blue and green of the existing buttons?

2023-07-10 01:51 UTC, jmsargent10 approved these changes
LGTM! Solid work!

2023-07-10 01:56 UTC, mike10911 approved these changes
LGTM!!!!

2023-07-10 15:57 UTC, merged