Aj export csv
HackBeanpot/internal-tools pull request #141
Opened 2023-07-12 03:51 UTC by jmsargent10

Fixes #101 

Wrapped the existing “Export CSV” button with something called a CSVLink which allows you to export a react object as a CSV file, with given data and headers, when clicked. You can read more about it [here](https://www.npmjs.com/package/react-csv).

Changed cabinValues to be a list of lists instead of a dictionary so that it could comply with the CSVLink expected format of either an array of arrays, or an array of objects.
This change affected selectedCabin.tsx because before its useState was a string (a key from the cabinValues dict), but we needed it to be a number so we could index the list. We confirmed it still works as expected.

Added two forEach loops to rearrange the emails in the exported CSV, as they were originally being displayed with the row and column positions swapped.

When you click the “Export CSV” Button:

What the CSV file looks like in raw format and then in table form:

N.B. One slight limitation is that there doesn’t seem to be a way to change the name of the file being downloaded…

2023-07-12 13:53 UTC, kzeng24 commented
Extra comments:
1. The cabin sorting link in the internal dashboard is missing - I think it was accidentally removed during merging.
2. When I accessed your branch, inside CSVCabinTable.tsx, it said that StyledTableHeader is missing so make sure to commit the StyledTableHeader in common.ts

2023-07-13 12:06 UTC, mike10911 requested changes
Awesome work guys! I'm also getting the issue of seeing HTML in the csv. It's possible that when addressing merge conflicts/rebasing, you might have undone that fix. 

P.S. don't worry about the file name issue, that feature is waiting for merge conflicts to be resolved to be merged in the react-csv repo. We can update this later!
https://github.com/react-csv/react-csv/pull/137

2023-07-13 13:42 UTC, Mandy-cyber commented on ui/components/templateDropdown/selectedCabin.tsx
> +          value={cabinNames[selectedItem]}
With the previous implementation, selectedItem was a string and was representative of a key in the cabinValues dictionary. But now that cabinValues is no loner a dict, and instead an array of arrays, we have to use integer indexing. Hope that answers that? Idk.

2023-07-13 13:43 UTC, Mandy-cyber commented on yarn.lock
> +<<<<<<< HEAD
good catch, thanks!

2023-07-13 17:25 UTC, Aaryan1203 approved these changes
Great work guys! I didn't find anything that needed any edits apart from a couple of the previous comments and I think you should be good to merge!

2023-07-16 01:02 UTC, kzeng24 reviewed
I still get this when I click on Export CSV :0
<img width="962" alt="Screen Shot 2023-07-15 at 9 01 36 PM" src="https://github.com/HackBeanpot/internal-tools/assets/52469441/1d1b11c6-2f96-41bd-adcb-0430460b2991">

2023-07-16 15:46 UTC, mike10911 approved these changes
LGTM!

2023-07-18 23:33 UTC, kzeng24 approved these changes
Approved! Nice job guys!!

2023-07-19 01:02 UTC, merged