Sg ky lj nextauth2
HackBeanpot/internal-tools pull request #17
Opened 2022-06-18 16:07 UTC by jhylisa666

Added authentication for internal tools. 
Added sign-in and sign-out using Google Authentication. 
Acceptance criteria:

 User cannot access any page of our tools application unless they are logged in
 User can sign in via email if not logged in and sign out if logged in
 Only users with the an email within our domain (@hackbeanpot.com) can login. Otherwise, display an error indicating the user is not authorized to view our tools.

https://user-images.githubusercontent.com/92692037/174447040-288834fb-eebc-4fd3-882f-d9fc381c71c7.mov

** Styling is off but is fixed in Judy and Dhivas's styling PR ^^

2022-06-18 21:04 UTC, jzhzhang66 requested changes
It's working for me! The styling is fixed in the other PR so this PR looks good to me! 

Just remove the comments and then I'm ready to approve. Thanks!

2022-06-18 21:04 UTC, jzhzhang66 commented on pages/_app.tsx
> +      // Provider options are not required but can be useful in situations where
Remove all comments

2022-06-18 21:04 UTC, jzhzhang66 commented on pages/api/auth/[...nextauth].js
> +// dynamic route handler
Remove all comments in files

2022-06-19 10:55 UTC, Dhivas-Sugumar reviewed
Works great for me! Approved

2022-06-19 16:22 UTC, jhylisa666 commented on pages/_app.tsx
> +      // Provider options are not required but can be useful in situations where
just removed!

2022-06-19 21:51 UTC, jzhzhang66 approved these changes
QUEEENS

2022-06-19 23:23 UTC, merged