aded signout button on navbar
HackBeanpot/internal-tools pull request #27
Opened 2022-06-24 13:43 UTC by jhylisa666

* Create a component Layout in /components/layout/Layout.tsx and add all your styles for Layout (if any) in /components/layout/Layout.styles.ts
*  Inside Layout.tsx create a navbar -> see these docs https://mui.com/material-ui/react-app-bar/
 * Add the signout button onto the navbar (this should be the only thing on there) and verify signing out still works as expected
 * Wrap all the pages with the Layout component. After you do this, you should see the navbar on all of the pages
*  Make sure the nav bar is responsive and looks good from mobile -> desktop

Video --> 
https://user-images.githubusercontent.com/92692037/175548254-302371bb-2ea3-48e3-9018-c48b2668a38c.mov

2022-06-24 17:07 UTC, jzhzhang66 requested changes
HEY LISAAA<333 Thank you so much for working on this - you're doing great!! Super proud of ya for taking this on:)) You got the general idea - just left a few comments on how we can improve this even more! 

Also, sx is inline styling and as per our styling guide, if we want to style things we are using the styled utility from MUI. It seems like a lot of your sx styling isn't actually doing anything so for those we can remove them. But if you have a styling you intentionally do want and it is doing something, use the styled utility. You can see examples of how to do this in the files in /pageStyles folder!!!

2022-06-24 17:07 UTC, jzhzhang66 commented on package.json
> +    "@mui/icons-material": "^5.8.4",
yarn remove this package (b/c we don't need the hamburger icon or any other icons from this package right now)

2022-06-25 00:46 UTC, karynayen requested changes
OMG AMAZING WORK LISA!!! I also agree with judy about the color! maybe make the inner text white? and maybe make the button transparent with a white outline? or change the color so that it fits more with the themes? Whatever you think will look best!!

2022-06-26 15:53 UTC, jhylisa666 commented on pages/emailSender.tsx
> +      <Button variant="contained" color = "secondary">
Woahhhhhh I seeeeee thankssss!!!!!!!

2022-06-27 02:11 UTC, jzhzhang66 approved these changes
BEAUT

2022-06-27 02:51 UTC, karynayen approved these changes
LOOKS GREAT!!

2022-06-27 02:55 UTC, merged