Add error handling to signature maker.
HackBeanpot/internal-tools pull request #36
Opened 2022-06-27 04:33 UTC by surbhi-gulati

Fixes [#18](https://github.com/HackBeanpot/internal-tools/issues/18).

- If the name, title, phone, or email field is empty, then there is an error for that field
- Clicking generate signature does not generate a signature if there are errors

2022-06-27 14:12 UTC, jzhzhang66 requested changes
This looks great!! Just a few comments: 
- Can we make the inputs wider? Similar to the width from before? We have enough space and it'd be nice to see the whole @hackbeanpot.com placeholder
<img width="296" alt="Screen Shot 2022-06-27 at 10 08 49 AM" src="https://user-images.githubusercontent.com/59738880/175961216-310aeda1-ca8d-440e-ac96-affb62ff9ba5.png">
- The deploy is failing with the following error which prevents us from merging this
<img width="1221" alt="Screen Shot 2022-06-27 at 10 09 52 AM" src="https://user-images.githubusercontent.com/59738880/175961431-458d70bc-8710-4025-b00e-3c973446d9dd.png">
 
If you search the error on google there's several solutions so I recommend trying these out https://stackoverflow.com/questions/41462729/typescript-react-could-not-find-a-declaration-file-for-module-react-material

2022-06-28 16:43 UTC, Dhivas-Sugumar approved these changes
Great PR, looks good to me! Just add Judy's requested changes and should be gtg!

2022-06-29 06:09 UTC, surbhi-gulati commented
Fixed! PTAL @jzhzhang66

2022-06-29 13:55 UTC, jzhzhang66 requested changes
Nice job fixing the module! Left a few other comments - lmk if u have questions!!

2022-06-29 13:55 UTC, jzhzhang66 commented on pages/sigmaker.tsx
> +                sx={{width:220}}
We don't want to use inline styling - to make this button wider you can use width="medium"

2022-06-29 13:55 UTC, jzhzhang66 commented on pages/sigmaker.tsx
> +    <TextValidator
To increase the input width, you'd want to create something like StyledTextValidator in sigmaker.styles.ts and set the width there. Then use StyledTextValidator here instead. I think a width of 275 or 280 would be pretty similar to what we had before! You can look at the way other components are styled for reference:)

2022-06-29 13:55 UTC, jzhzhang66 commented on pages/sigmaker.tsx
> +          <div>
Somehow this button got re-added in - let's remove it (delete lines 182-186)

2022-06-30 13:34 UTC, jzhzhang66 approved these changes
LGTM!!!

2022-06-30 20:17 UTC, merged