Redirect signin
HackBeanpot/internal-tools pull request #39
Opened 2022-06-29 11:49 UTC by Dhivas-Sugumar

Closes #29 

- The user is redirected to sign in if there is no session data on all pages. Based the solution off of the application portal as recommended. 
- Removed the unstyled signout button at the end. 

The only page an unauthorized user can access.
![image](https://user-images.githubusercontent.com/65351416/176429208-f4b2c49a-62d2-4610-b7f1-db040e129e68.png)

Removed unstyled sign out button. 
![image](https://user-images.githubusercontent.com/65351416/176429492-8ffb9c2b-34e0-4779-9e0c-f29faf25ca97.png)

2022-06-29 14:24 UTC, jzhzhang66 requested changes
NICE JOBBBB!!! Looks great! 

The only comment I have is to remove all unused imports / variables. In emailSender.tsx, index.tsx, and sigmaker.tsx all imports from next-auth/react should be removed since they're not being used

2022-06-29 14:24 UTC, jzhzhang66 commented on pages/index.tsx
>    const { data: session } = useSession()
Removed unused var

2022-06-30 10:43 UTC, Dhivas-Sugumar commented on pages/index.tsx
>    const { data: session } = useSession()
Removed unused imports.

2022-06-30 13:37 UTC, jzhzhang66 approved these changes
LGTM!!!:)

2022-06-30 18:09 UTC, mike10911 approved these changes
Looks so beautiful! Great job!

2022-06-30 20:28 UTC, merged