add functionality
HackBeanpot/internal-tools pull request #49
Opened 2022-07-11 19:30 UTC by karynayen

Closes #48 

Add a popup when clicking send that asks the user:  'Are you sure you want to send all emails?' and then a yes and no button. Emails are only sent if the 'yes' button is pressed.

https://user-images.githubusercontent.com/37753574/178343063-2bc74e9d-12fc-478e-a1fb-e33b9e30db3a.mov

2022-07-11 20:22 UTC, jzhzhang66 requested changes
Looks amazing!!!! You're killin it karyna:)))) 

Just one small comment and I was also wondering if your pre-commit hook is working? 

There's some eslint errors - when you run yarn run lint or commit your stuff do you see any errors? 
<img width="577" alt="Screen Shot 2022-07-11 at 4 22 10 PM" src="https://user-images.githubusercontent.com/59738880/178351374-beac9bb7-51a2-4746-8d14-6d1cfadecb51.png">

2022-07-11 20:22 UTC, jzhzhang66 commented on pages/emailSender.tsx
> +                {"Are you sure you want to send all emails?"}
We don't need to add the curly brackets and quotes here - you can just change to Are you sure you want to send all emails?

2022-07-11 22:39 UTC, karynayen commented
omg I finally fixed the pre-commit issue, it turns out I had an extra node-modules directory folder outside of the main directory that was causing an issue! I just had to delete it and it worked!

2022-07-11 22:42 UTC, karynayen commented
hmm also I ended up re-cloning and reinstalling everything and the version types changed... is that ok?

2022-07-12 02:38 UTC, jzhzhang66 approved these changes
NICE JOB KARYNAAAA<33333

2022-07-12 02:48 UTC, deanframe approved these changes
Looks mostly great! Fix this then merge :D

2022-07-12 02:48 UTC, deanframe commented on pages/emailSender.tsx
> +              aria-describedby="alert-dialog-description"
We don't have a DialogContent or DialogContentText, so no need for this `aria-describedby` label

2022-07-12 20:06 UTC, merged