Dynamically retrieve sender using session hook, correctly display on Outlook.
HackBeanpot/internal-tools pull request #55
Opened 2022-07-17 05:23 UTC by surbhi-gulati

Fixes [#46](https://github.com/HackBeanpot/internal-tools/issues/46).

- Removes hardcoding of email sender by extracting name and email of sender from useSession hook to form Mailgun request
- Displays sender in pretty format on Outlook by using "h:sender" field to override default mailgun behavior of saying Mailgun sent email on behalf of HBP domain

 (ie sender reads "Surbhi Gulati <surbhi@hackbeanpot.com>" rather than "surbhi=hackbeanpot.com@mailgun.hackbeanpot.com on behalf of Surbhi Gulati <surbhi@hackbeanpot.com>")

After fixing both of these, email renders like so:
![7_16 outlook email ](https://user-images.githubusercontent.com/53664026/179385043-1244864c-ab80-4296-910a-f11019cc629e.png)

2022-07-17 14:50 UTC, jzhzhang66 approved these changes
LGTM!! There was an issue on main so after you merged main into your branch the email sender page stopped compiling.

I just pushed a fix for the issue on main so please pull from main and then merge main into your branch and make sure everything is working then you're good to merge after dhivas' review / approval! 

@Dhivas-Sugumar to test this branch (if it's still not compiling when u review) you can just remove the StyledFinalMessageContent for now
<img width="782" alt="Screen Shot 2022-07-17 at 10 48 56 AM" src="https://user-images.githubusercontent.com/59738880/179403852-04cb3de3-5cdf-40a4-8f92-704acd9b43a2.png">

2022-07-17 15:54 UTC, jzhzhang66 requested changes

2022-07-17 15:54 UTC, jzhzhang66 commented on pages/emailSender.tsx
> +  const { data: session, status } = useSession({ required: true })
jk I just realized status is never used - let's remove it

2022-07-17 21:24 UTC, Dhivas-Sugumar approved these changes
LGTM! Great PR!

2022-07-18 18:14 UTC, jzhzhang66 approved these changes

2022-07-19 02:53 UTC, merged