Create PR template in new general docs folder.
HackBeanpot/internal-tools pull request #71
Opened 2022-07-31 07:54 UTC by surbhi-gulati

Introduces a PR template to help us standardize commits quality.

Partially resolves #[67](https://github.com/HackBeanpot/internal-tools/issues/67).

Notes:
- Followed Github docs to create the PR template:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
- Using the proposed PR structure for this! How meta

Tested:
N/A, will use it to create a new PR and manual test after it is first merged in.

2022-07-31 13:43 UTC, jzhzhang66 requested changes
Overall looks great! 

One comment - could we make the screenshots bullet into a separate section?

2022-07-31 17:22 UTC, jzhzhang66 approved these changes

2022-08-01 00:17 UTC, Dhivas-Sugumar approved these changes
LGTM!

2022-08-01 00:51 UTC, mike10911 approved these changes
Great work! This is sooo cool!!!!

2022-08-01 03:51 UTC, merged