Update help page
HackBeanpot/internal-tools pull request #85
Opened 2022-08-13 06:56 UTC by mike10911

Updated Email Sender Help Page

Fixes #80 

Changelist:
- Detailed how to add a customized HBP signature
- Detailed where to find instructions on how to cancel a scheduled email (Mailgun dashboard)
- Detailed when scheduled emails are sent across different timezones
- Detailed Mailgun's load
- Noted that the user should use Google Sheets to export their CSV

Tested:
- Ran on localhost:3000
  
Screenshots & Screencasts:

_In order of change list_

<img width="966" alt="Screen Shot 2022-08-13 at 2 28 11 AM" src="https://user-images.githubusercontent.com/103906123/184472020-fd8130dc-9a11-4388-afed-a39555ccd24d.png">

<img width="943" alt="Screen Shot 2022-08-13 at 2 32 00 AM" src="https://user-images.githubusercontent.com/103906123/184472022-a3eac0b0-ccbe-4ca8-86ba-a52062798c84.png">

<img width="954" alt="Screen Shot 2022-08-13 at 2 32 48 AM" src="https://user-images.githubusercontent.com/103906123/184472027-bb27abbd-34cc-4df8-99ce-e8cb7c54534c.png">

<img width="652" alt="Screen Shot 2022-08-13 at 2 33 26 AM" src="https://user-images.githubusercontent.com/103906123/184472030-ceebe479-218d-4127-a72d-d4d256f6c098.png">

<img width="882" alt="Screen Shot 2022-08-13 at 2 34 32 AM" src="https://user-images.githubusercontent.com/103906123/184472032-32f0a7aa-0658-43a2-b768-d67876148f49.png">

2022-08-14 07:47 UTC, jzhzhang66 approved these changes
oops accidentally approved w/ hackbeanbot LOL - approving with my account xd

2022-08-14 14:00 UTC, jhylisa666 requested changes
Should we indicate that all scheduled times are in EST? even for those emails sent to ppl in different time zones. otherwise GOOOOOD JOBBBBBBB

2022-08-15 02:36 UTC, jhylisa666 commented
> 

I think when i was making the customizable send thing with Judy and Mike, we coded that it will always be sent in EST, but i can double check!

2022-08-16 15:17 UTC, jhylisa666 approved these changes
YASSS KINGGGG GOOD JOB

2022-08-16 19:17 UTC, merged