Connect MongoDB
HackBeanpot/internal-tools pull request #88
Opened 2022-09-24 19:08 UTC by mike10911

Establish GET endpoint and MongoDB connection

Fixes #87 

Changelist:
- Added mongo.ts to handle the connection to templates database on MongoDB Atlas
- Removed previous mock templates and data handling logic and replace with GET logic for Mongo
- 

Notes:
- Installed MongoDB
- Installed next-connect

Tested:
- Tested by inserting data in MongoDB Atlas and hitting the endpoint on our local machine

<img width="1800" alt="Screen Shot 2022-09-24 at 3 06 30 PM" src="https://user-images.githubusercontent.com/103906123/192114582-f045a875-f6ac-4c2c-ac44-3cab9ec69263.png">
<img width="3360" alt="Screen Shot 2022-09-24 at 3 06 30 PM (2)" src="https://user-images.githubusercontent.com/103906123/192114583-c0116fba-d473-4cd5-9412-37c5e84878c1.png">
ongoDB Atlas and hitting the endpoint on our local machine

2022-09-24 22:16 UTC, jzhzhang66 requested changes
Overall looks fantastic!!!! BACKEND KINGSSSSSS<333 and s/o to @deanframe for being a fantastic mentor!!<3 

Could we also add logic to make sure that people can't access the data when they're not signed in? 

https://user-images.githubusercontent.com/59738880/192120474-5604941d-ec65-442d-9d46-d7dc3de65a72.mov

Also, please make sure to add the .env variable on vercel if u haven't yet! I haven't checked the error but this might be the issue

2022-09-24 22:16 UTC, jzhzhang66 commented on pages/api/templates.js
> +  const res = await fetch('http://localhost:3000/api/templates', {
You can change this to just /api/templates! Right now this will only work for localhost but not production

2022-09-28 03:49 UTC, jhylisa666 approved these changes
LGTMMM!!!!!!! YALLLL SOOOOO SMARTTTTTT

2022-09-29 03:00 UTC, jzhzhang66 commented
The endpoint can still be accessed when not signed in - here's what a fix would look like (kind of also related to our workshop content heh): 

You get the request session and if there is a session, then show the data. Otherwise, send a 401 status code w / a nice little message that the unauthorized user will receive. 

<img width="700" alt="Screen Shot 2022-09-28 at 10 59 09 PM" src="https://user-images.githubusercontent.com/59738880/192928683-1cd033f8-8c88-40c0-b86a-1831bf464210.png">

2022-09-29 13:14 UTC, jzhzhang66 approved these changes
LGTM

2022-09-29 13:30 UTC, merged